# fly.toml app configuration file generated for phonebookforkonala on 2023-09-19T14:03:52+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phonebookforkonala"
primary_region = "ams"

[build]

[env]
  PORT = "5173"

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
